In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
house = pd.read_csv('housing.csv')
house

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [21]:
X = house.drop('median_house_value', axis=1)
y = house.median_house_value

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=121)

In [24]:
X_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
5800,-118.24,34.15,7.0,2063.0,670.0,1892.0,643.0,1.7301,<1H OCEAN
601,-122.08,37.70,25.0,3402.0,758.0,1645.0,710.0,3.4934,NEAR BAY
10379,-117.64,33.65,4.0,6842.0,1512.0,3256.0,1439.0,5.4132,<1H OCEAN
20405,-118.88,34.21,26.0,1590.0,196.0,654.0,199.0,6.5851,<1H OCEAN
7170,-118.19,34.06,37.0,1715.0,456.0,2052.0,440.0,2.3125,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
19198,-122.69,38.44,31.0,1808.0,315.0,691.0,280.0,3.8583,<1H OCEAN
3583,-118.55,34.23,25.0,4409.0,1018.0,4579.0,1010.0,2.8727,<1H OCEAN
18497,-121.54,36.99,27.0,2361.0,449.0,1782.0,397.0,3.2614,INLAND
4565,-118.26,34.07,40.0,680.0,273.0,995.0,249.0,2.2607,<1H OCEAN
11586,-118.01,33.79,30.0,2460.0,403.0,1277.0,395.0,5.4372,<1H OCEAN

In [25]:
X_test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
16818,-122.46,37.65,16.0,8676.0,1633.0,5130.0,1574.0,4.8096,NEAR OCEAN
18306,-122.11,37.43,35.0,3905.0,565.0,1562.0,553.0,7.3130,NEAR BAY
549,-122.25,37.77,52.0,2156.0,458.0,872.0,445.0,3.2685,NEAR BAY
4239,-118.32,34.11,42.0,2462.0,543.0,857.0,482.0,4.0833,<1H OCEAN
6084,-117.89,34.09,36.0,1811.0,320.0,1005.0,332.0,5.5629,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
6460,-118.05,34.10,36.0,1606.0,318.0,889.0,294.0,4.7931,INLAND
18375,-121.85,37.22,21.0,6203.0,798.0,2494.0,800.0,7.7201,<1H OCEAN
11212,-117.91,33.82,29.0,1444.0,326.0,1038.0,271.0,2.3843,<1H OCEAN
20291,-119.19,34.17,35.0,4276.0,767.0,3295.0,708.0,4.2583,NEAR OCEAN
6340,-117.90,33.98,20.0,9893.0,2283.0,7228.0,2159.0,3.2530,<1H OCEAN

In [26]:
X_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
5800,-118.24,34.15,7.0,2063.0,670.0,1892.0,643.0,1.7301,<1H OCEAN
601,-122.08,37.70,25.0,3402.0,758.0,1645.0,710.0,3.4934,NEAR BAY
10379,-117.64,33.65,4.0,6842.0,1512.0,3256.0,1439.0,5.4132,<1H OCEAN
20405,-118.88,34.21,26.0,1590.0,196.0,654.0,199.0,6.5851,<1H OCEAN
7170,-118.19,34.06,37.0,1715.0,456.0,2052.0,440.0,2.3125,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
19198,-122.69,38.44,31.0,1808.0,315.0,691.0,280.0,3.8583,<1H OCEAN
3583,-118.55,34.23,25.0,4409.0,1018.0,4579.0,1010.0,2.8727,<1H OCEAN
18497,-121.54,36.99,27.0,2361.0,449.0,1782.0,397.0,3.2614,INLAND
4565,-118.26,34.07,40.0,680.0,273.0,995.0,249.0,2.2607,<1H OCEAN
11586,-118.01,33.79,30.0,2460.0,403.0,1277.0,395.0,5.4372,<1H OCEAN

In [31]:
X_train_num = X_train.select_dtypes('float')
X_train_cat = X_train.select_dtypes('object')

In [32]:
X_test_num = X_test.select_dtypes('float')
X_test_cat = X_test.select_dtypes('object')

In [33]:
X_train_num

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
5800,-118.24,34.15,7.0,2063.0,670.0,1892.0,643.0,1.7301
601,-122.08,37.70,25.0,3402.0,758.0,1645.0,710.0,3.4934
10379,-117.64,33.65,4.0,6842.0,1512.0,3256.0,1439.0,5.4132
20405,-118.88,34.21,26.0,1590.0,196.0,654.0,199.0,6.5851
7170,-118.19,34.06,37.0,1715.0,456.0,2052.0,440.0,2.3125
...,...,...,...,...,...,...,...,...
19198,-122.69,38.44,31.0,1808.0,315.0,691.0,280.0,3.8583
3583,-118.55,34.23,25.0,4409.0,1018.0,4579.0,1010.0,2.8727
18497,-121.54,36.99,27.0,2361.0,449.0,1782.0,397.0,3.2614
4565,-118.26,34.07,40.0,680.0,273.0,995.0,249.0,2.2607
11586,-118.01,33.79,30.0,2460.0,403.0,1277.0,395.0,5.4372

In [34]:
X_train_cat

      ocean_proximity
5800        <1H OCEAN
601          NEAR BAY
10379       <1H OCEAN
20405       <1H OCEAN
7170        <1H OCEAN
...               ...
19198       <1H OCEAN
3583        <1H OCEAN
18497          INLAND
4565        <1H OCEAN
11586       <1H OCEAN

[16512 rows x 1 columns]

In [35]:
X_test_num

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
16818,-122.46,37.65,16.0,8676.0,1633.0,5130.0,1574.0,4.8096
18306,-122.11,37.43,35.0,3905.0,565.0,1562.0,553.0,7.3130
549,-122.25,37.77,52.0,2156.0,458.0,872.0,445.0,3.2685
4239,-118.32,34.11,42.0,2462.0,543.0,857.0,482.0,4.0833
6084,-117.89,34.09,36.0,1811.0,320.0,1005.0,332.0,5.5629
...,...,...,...,...,...,...,...,...
6460,-118.05,34.10,36.0,1606.0,318.0,889.0,294.0,4.7931
18375,-121.85,37.22,21.0,6203.0,798.0,2494.0,800.0,7.7201
11212,-117.91,33.82,29.0,1444.0,326.0,1038.0,271.0,2.3843
20291,-119.19,34.17,35.0,4276.0,767.0,3295.0,708.0,4.2583
6340,-117.90,33.98,20.0,9893.0,2283.0,7228.0,2159.0,3.2530

In [36]:
X_test_cat

      ocean_proximity
16818      NEAR OCEAN
18306        NEAR BAY
549          NEAR BAY
4239        <1H OCEAN
6084        <1H OCEAN
...               ...
6460           INLAND
18375       <1H OCEAN
11212       <1H OCEAN
20291      NEAR OCEAN
6340        <1H OCEAN

[4128 rows x 1 columns]

In [37]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [40]:
impute = SimpleImputer(strategy='median')
impute.fit(X_train_num)                      # we only fit the train data not test data
X_train_num_tr = impute.transform(X_train_num)
X_test_num_tr = impute.transform(X_test_num)

In [41]:
X_train_num_tr

array([[-1.1824e+02,  3.4150e+01,  7.0000e+00, ...,  1.8920e+03,
         6.4300e+02,  1.7301e+00],
       [-1.2208e+02,  3.7700e+01,  2.5000e+01, ...,  1.6450e+03,
         7.1000e+02,  3.4934e+00],
       [-1.1764e+02,  3.3650e+01,  4.0000e+00, ...,  3.2560e+03,
         1.4390e+03,  5.4132e+00],
       ...,
       [-1.2154e+02,  3.6990e+01,  2.7000e+01, ...,  1.7820e+03,
         3.9700e+02,  3.2614e+00],
       [-1.1826e+02,  3.4070e+01,  4.0000e+01, ...,  9.9500e+02,
         2.4900e+02,  2.2607e+00],
       [-1.1801e+02,  3.3790e+01,  3.0000e+01, ...,  1.2770e+03,
         3.9500e+02,  5.4372e+00]])

In [42]:
X_train_num_tr.shape

(16512, 8)

In [43]:
X_train_num

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
5800,-118.24,34.15,7.0,2063.0,670.0,1892.0,643.0,1.7301
601,-122.08,37.70,25.0,3402.0,758.0,1645.0,710.0,3.4934
10379,-117.64,33.65,4.0,6842.0,1512.0,3256.0,1439.0,5.4132
20405,-118.88,34.21,26.0,1590.0,196.0,654.0,199.0,6.5851
7170,-118.19,34.06,37.0,1715.0,456.0,2052.0,440.0,2.3125
...,...,...,...,...,...,...,...,...
19198,-122.69,38.44,31.0,1808.0,315.0,691.0,280.0,3.8583
3583,-118.55,34.23,25.0,4409.0,1018.0,4579.0,1010.0,2.8727
18497,-121.54,36.99,27.0,2361.0,449.0,1782.0,397.0,3.2614
4565,-118.26,34.07,40.0,680.0,273.0,995.0,249.0,2.2607
11586,-118.01,33.79,30.0,2460.0,403.0,1277.0,395.0,5.4372

In [44]:
X_train_num.shape

(16512, 8)

In [45]:
scale = StandardScaler()
scale.fit(X_train_num_tr)
X_train_num_tr = scale.transform(X_train_num_tr)
X_test_num_tr = scale.transform(X_test_num_tr)

In [46]:
X_train_num_tr

array([[ 0.66136173, -0.69064867, -1.71479173, ...,  0.41204053,
         0.38008101, -1.12465992],
       [-1.25933122,  0.97054898, -0.28418936, ...,  0.19457453,
         0.55678574, -0.19477467],
       [ 0.96147001, -0.92462017, -1.95322546, ...,  1.61294591,
         2.47943863,  0.81764165],
       ...,
       [-0.98923378,  0.63830945, -0.12523354, ...,  0.31519332,
        -0.26871543, -0.31712105],
       [ 0.65135812, -0.72808411,  0.90797928, ..., -0.37770443,
        -0.65904826, -0.8448453 ],
       [ 0.77640324, -0.85910815,  0.11320019, ..., -0.12942341,
        -0.2739902 ,  0.83029817]])

In [47]:
X_test_num_tr

array([[-1.4493998 ,  0.94715183, -0.99949055, ...,  3.26287017,
         2.83548546,  0.49933011],
       [-1.27433664,  0.84420437,  0.51058973, ...,  0.12149891,
         0.14271646,  1.81951086],
       [-1.3443619 ,  1.00330499,  1.8617142 , ..., -0.48599722,
        -0.142121  , -0.31337683],
       ...,
       [ 0.82642128, -0.84506986,  0.03372228, ..., -0.33984598,
        -0.60102581, -0.77966421],
       [ 0.1861903 , -0.68128981,  0.51058973, ...,  1.64728265,
         0.55151097,  0.20859924],
       [ 0.83142309, -0.77019898, -0.68157891, ...,  5.11001057,
         4.37835506, -0.32155084]])

In [48]:
X_train_cat

      ocean_proximity
5800        <1H OCEAN
601          NEAR BAY
10379       <1H OCEAN
20405       <1H OCEAN
7170        <1H OCEAN
...               ...
19198       <1H OCEAN
3583        <1H OCEAN
18497          INLAND
4565        <1H OCEAN
11586       <1H OCEAN

[16512 rows x 1 columns]

In [50]:
X_test_cat

      ocean_proximity
16818      NEAR OCEAN
18306        NEAR BAY
549          NEAR BAY
4239        <1H OCEAN
6084        <1H OCEAN
...               ...
6460           INLAND
18375       <1H OCEAN
11212       <1H OCEAN
20291      NEAR OCEAN
6340        <1H OCEAN

[4128 rows x 1 columns]

In [63]:
encoder = OrdinalEncoder()
encoder.fit(X_train_cat)
X_train_cat_tr = encoder.transform(X_train_cat)
X_test_cat_tr = encoder.transform(X_test_cat)

In [64]:
X_train_cat_tr

array([[0.],
       [3.],
       [0.],
       ...,
       [1.],
       [0.],
       [0.]])

In [65]:
X_test_cat_tr

array([[4.],
       [3.],
       [3.],
       ...,
       [0.],
       [4.],
       [0.]])

In [66]:
X_train_num_tr

array([[ 0.66136173, -0.69064867, -1.71479173, ...,  0.41204053,
         0.38008101, -1.12465992],
       [-1.25933122,  0.97054898, -0.28418936, ...,  0.19457453,
         0.55678574, -0.19477467],
       [ 0.96147001, -0.92462017, -1.95322546, ...,  1.61294591,
         2.47943863,  0.81764165],
       ...,
       [-0.98923378,  0.63830945, -0.12523354, ...,  0.31519332,
        -0.26871543, -0.31712105],
       [ 0.65135812, -0.72808411,  0.90797928, ..., -0.37770443,
        -0.65904826, -0.8448453 ],
       [ 0.77640324, -0.85910815,  0.11320019, ..., -0.12942341,
        -0.2739902 ,  0.83029817]])

In [67]:
X_train_cat_tr

array([[0.],
       [3.],
       [0.],
       ...,
       [1.],
       [0.],
       [0.]])

In [68]:
X_train_tr = np.concatenate((X_train_num_tr, X_train_cat_tr), axis=1)
X_train_tr

array([[ 0.66136173, -0.69064867, -1.71479173, ...,  0.38008101,
        -1.12465992,  0.        ],
       [-1.25933122,  0.97054898, -0.28418936, ...,  0.55678574,
        -0.19477467,  3.        ],
       [ 0.96147001, -0.92462017, -1.95322546, ...,  2.47943863,
         0.81764165,  0.        ],
       ...,
       [-0.98923378,  0.63830945, -0.12523354, ..., -0.26871543,
        -0.31712105,  1.        ],
       [ 0.65135812, -0.72808411,  0.90797928, ..., -0.65904826,
        -0.8448453 ,  0.        ],
       [ 0.77640324, -0.85910815,  0.11320019, ..., -0.2739902 ,
         0.83029817,  0.        ]])

In [69]:
X_train_tr.shape

(16512, 9)

In [70]:
X_test_tr = np.concatenate((X_test_num_tr, X_test_cat_tr), axis=1)
X_test_tr

array([[-1.4493998 ,  0.94715183, -0.99949055, ...,  2.83548546,
         0.49933011,  4.        ],
       [-1.27433664,  0.84420437,  0.51058973, ...,  0.14271646,
         1.81951086,  3.        ],
       [-1.3443619 ,  1.00330499,  1.8617142 , ..., -0.142121  ,
        -0.31337683,  3.        ],
       ...,
       [ 0.82642128, -0.84506986,  0.03372228, ..., -0.60102581,
        -0.77966421,  0.        ],
       [ 0.1861903 , -0.68128981,  0.51058973, ...,  0.55151097,
         0.20859924,  4.        ],
       [ 0.83142309, -0.77019898, -0.68157891, ...,  4.37835506,
        -0.32155084,  0.        ]])

In [71]:
X_test_tr.shape

(4128, 9)

In [72]:
from sklearn.linear_model import LinearRegression, SGDRegressor

In [73]:
from sklearn.metrics import r2_score, mean_squared_error

In [74]:
model = LinearRegression()
model.fit(X_train_tr, y_train)
y_train_hat = model.predict(X_train_tr)
y_test_hat = model.predict(X_test_tr)

print(f"Training Accuracy: {r2_score(y_train, y_train_hat)}")
print(f"Training error: {mean_squared_error(y_train, y_train_hat)}")
print()
print(f"Testing Accuracy: {r2_score(y_test, y_test_hat)}")
print(f"Testing error: {mean_squared_error(y_test, y_test_hat)}")

Training Accuracy: 0.6302837145718101
Training error: 4926615676.883583

Testing Accuracy: 0.6565099331108482
Testing error: 4559838180.699618

In [38]:
model = SGDRegressor()
model.fit(X_train_tr, y_train)
y_train_hat = model.predict(X_train_tr)
y_test_hat = model.predict(X_test_tr)

print(f"Training Accuracy: {r2_score(y_train, y_train_hat)}")
print(f"Training error: {mean_squared_error(y_train, y_train_hat)}")
print()
print(f"Testing Accuracy: {r2_score(y_test, y_test_hat)}")
print(f"Testing error: {mean_squared_error(y_test, y_test_hat)}")

Training Accuracy: 0.6296507883680957
Training error: 4935049668.7860985

Testing Accuracy: 0.6556793164009255
Testing error: 4570864635.763471

# **PipeLines**
##### - Used to automate the process

In [39]:
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,INLAND

In [40]:
X_train_num

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
5800,-118.24,34.15,7.0,2063.0,670.0,1892.0,643.0,1.7301
601,-122.08,37.70,25.0,3402.0,758.0,1645.0,710.0,3.4934
10379,-117.64,33.65,4.0,6842.0,1512.0,3256.0,1439.0,5.4132
20405,-118.88,34.21,26.0,1590.0,196.0,654.0,199.0,6.5851
7170,-118.19,34.06,37.0,1715.0,456.0,2052.0,440.0,2.3125
...,...,...,...,...,...,...,...,...
19198,-122.69,38.44,31.0,1808.0,315.0,691.0,280.0,3.8583
3583,-118.55,34.23,25.0,4409.0,1018.0,4579.0,1010.0,2.8727
18497,-121.54,36.99,27.0,2361.0,449.0,1782.0,397.0,3.2614
4565,-118.26,34.07,40.0,680.0,273.0,995.0,249.0,2.2607
11586,-118.01,33.79,30.0,2460.0,403.0,1277.0,395.0,5.4372

In [41]:
X_test_num

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
16818,-122.46,37.65,16.0,8676.0,1633.0,5130.0,1574.0,4.8096
18306,-122.11,37.43,35.0,3905.0,565.0,1562.0,553.0,7.3130
549,-122.25,37.77,52.0,2156.0,458.0,872.0,445.0,3.2685
4239,-118.32,34.11,42.0,2462.0,543.0,857.0,482.0,4.0833
6084,-117.89,34.09,36.0,1811.0,320.0,1005.0,332.0,5.5629
...,...,...,...,...,...,...,...,...
6460,-118.05,34.10,36.0,1606.0,318.0,889.0,294.0,4.7931
18375,-121.85,37.22,21.0,6203.0,798.0,2494.0,800.0,7.7201
11212,-117.91,33.82,29.0,1444.0,326.0,1038.0,271.0,2.3843
20291,-119.19,34.17,35.0,4276.0,767.0,3295.0,708.0,4.2583
6340,-117.90,33.98,20.0,9893.0,2283.0,7228.0,2159.0,3.2530

In [42]:
X_train_cat

      ocean_proximity
5800        <1H OCEAN
601          NEAR BAY
10379       <1H OCEAN
20405       <1H OCEAN
7170        <1H OCEAN
...               ...
19198       <1H OCEAN
3583        <1H OCEAN
18497          INLAND
4565        <1H OCEAN
11586       <1H OCEAN

[16512 rows x 1 columns]

In [43]:
X_test_cat

      ocean_proximity
16818      NEAR OCEAN
18306        NEAR BAY
549          NEAR BAY
4239        <1H OCEAN
6084        <1H OCEAN
...               ...
6460           INLAND
18375       <1H OCEAN
11212       <1H OCEAN
20291      NEAR OCEAN
6340        <1H OCEAN

[4128 rows x 1 columns]

In [44]:
from sklearn.pipeline import Pipeline

In [70]:
num_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy='median')),
    ('scale', StandardScaler())
])

cat_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder())
])

In [71]:
num_pipeline

Pipeline(steps=[('impute', SimpleImputer(strategy='median')),
                ('scale', StandardScaler())])

In [72]:
cat_pipeline

Pipeline(steps=[('impute', SimpleImputer(strategy='most_frequent')),
                ('encoder', OrdinalEncoder())])

In [48]:
num_pipeline.fit(X_train_num)
X_train_num_tr = num_pipeline.transform(X_train_num)
X_test_num_tr = num_pipeline.transform(X_test_num)

In [49]:
X_train_num_tr

array([[ 0.66136173, -0.69064867, -1.71479173, ...,  0.41204053,
         0.38008101, -1.12465992],
       [-1.25933122,  0.97054898, -0.28418936, ...,  0.19457453,
         0.55678574, -0.19477467],
       [ 0.96147001, -0.92462017, -1.95322546, ...,  1.61294591,
         2.47943863,  0.81764165],
       ...,
       [-0.98923378,  0.63830945, -0.12523354, ...,  0.31519332,
        -0.26871543, -0.31712105],
       [ 0.65135812, -0.72808411,  0.90797928, ..., -0.37770443,
        -0.65904826, -0.8448453 ],
       [ 0.77640324, -0.85910815,  0.11320019, ..., -0.12942341,
        -0.2739902 ,  0.83029817]])

In [50]:
cat_pipeline.fit(X_train_cat)
X_train_cat_tr = cat_pipeline.transform(X_train_cat)
X_test_cat_tr = cat_pipeline.transform(X_test_cat)

In [51]:
X_train_cat_tr

array([[0.],
       [3.],
       [0.],
       ...,
       [1.],
       [0.],
       [0.]])

In [52]:
num_pipeline.named_steps

{'impute': SimpleImputer(strategy='median'), 'scale': StandardScaler()}

In [53]:
num_pipeline.named_steps.scale

StandardScaler()

In [54]:
num_pipeline.named_steps.scale.mean_

array([-119.56224625,   35.62592478,   28.57570252, 2632.50914486,
        536.05159884, 1424.00036337,  498.8871124 ,    3.86274254])

In [55]:
num_pipeline.named_steps.scale.var_

array([3.99711424e+00, 4.56682210e+00, 1.58309555e+02, 4.70949367e+06,
       1.73162729e+05, 1.29006370e+06, 1.43765039e+05, 3.59578488e+00])

In [56]:
X_train_num_tr

array([[ 0.66136173, -0.69064867, -1.71479173, ...,  0.41204053,
         0.38008101, -1.12465992],
       [-1.25933122,  0.97054898, -0.28418936, ...,  0.19457453,
         0.55678574, -0.19477467],
       [ 0.96147001, -0.92462017, -1.95322546, ...,  1.61294591,
         2.47943863,  0.81764165],
       ...,
       [-0.98923378,  0.63830945, -0.12523354, ...,  0.31519332,
        -0.26871543, -0.31712105],
       [ 0.65135812, -0.72808411,  0.90797928, ..., -0.37770443,
        -0.65904826, -0.8448453 ],
       [ 0.77640324, -0.85910815,  0.11320019, ..., -0.12942341,
        -0.2739902 ,  0.83029817]])

In [57]:
X_train_cat_tr

array([[0.],
       [3.],
       [0.],
       ...,
       [1.],
       [0.],
       [0.]])

In [59]:
X_train_tr = np.concatenate((X_train_num_tr, X_train_cat_tr), axis=1)
X_train_tr

array([[ 0.66136173, -0.69064867, -1.71479173, ...,  0.38008101,
        -1.12465992,  0.        ],
       [-1.25933122,  0.97054898, -0.28418936, ...,  0.55678574,
        -0.19477467,  3.        ],
       [ 0.96147001, -0.92462017, -1.95322546, ...,  2.47943863,
         0.81764165,  0.        ],
       ...,
       [-0.98923378,  0.63830945, -0.12523354, ..., -0.26871543,
        -0.31712105,  1.        ],
       [ 0.65135812, -0.72808411,  0.90797928, ..., -0.65904826,
        -0.8448453 ,  0.        ],
       [ 0.77640324, -0.85910815,  0.11320019, ..., -0.2739902 ,
         0.83029817,  0.        ]])

In [60]:
X_test_tr = np.concatenate((X_test_num_tr, X_test_cat_tr), axis=1)
X_test_tr

array([[-1.4493998 ,  0.94715183, -0.99949055, ...,  2.83548546,
         0.49933011,  4.        ],
       [-1.27433664,  0.84420437,  0.51058973, ...,  0.14271646,
         1.81951086,  3.        ],
       [-1.3443619 ,  1.00330499,  1.8617142 , ..., -0.142121  ,
        -0.31337683,  3.        ],
       ...,
       [ 0.82642128, -0.84506986,  0.03372228, ..., -0.60102581,
        -0.77966421,  0.        ],
       [ 0.1861903 , -0.68128981,  0.51058973, ...,  0.55151097,
         0.20859924,  4.        ],
       [ 0.83142309, -0.77019898, -0.68157891, ...,  4.37835506,
        -0.32155084,  0.        ]])

# **Column transformer** 
    - Use for automate the process
    - Collection of multiple pipelines

In [62]:
X_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
5800,-118.24,34.15,7.0,2063.0,670.0,1892.0,643.0,1.7301,<1H OCEAN
601,-122.08,37.70,25.0,3402.0,758.0,1645.0,710.0,3.4934,NEAR BAY
10379,-117.64,33.65,4.0,6842.0,1512.0,3256.0,1439.0,5.4132,<1H OCEAN
20405,-118.88,34.21,26.0,1590.0,196.0,654.0,199.0,6.5851,<1H OCEAN
7170,-118.19,34.06,37.0,1715.0,456.0,2052.0,440.0,2.3125,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
19198,-122.69,38.44,31.0,1808.0,315.0,691.0,280.0,3.8583,<1H OCEAN
3583,-118.55,34.23,25.0,4409.0,1018.0,4579.0,1010.0,2.8727,<1H OCEAN
18497,-121.54,36.99,27.0,2361.0,449.0,1782.0,397.0,3.2614,INLAND
4565,-118.26,34.07,40.0,680.0,273.0,995.0,249.0,2.2607,<1H OCEAN
11586,-118.01,33.79,30.0,2460.0,403.0,1277.0,395.0,5.4372,<1H OCEAN

In [63]:
X_test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
16818,-122.46,37.65,16.0,8676.0,1633.0,5130.0,1574.0,4.8096,NEAR OCEAN
18306,-122.11,37.43,35.0,3905.0,565.0,1562.0,553.0,7.3130,NEAR BAY
549,-122.25,37.77,52.0,2156.0,458.0,872.0,445.0,3.2685,NEAR BAY
4239,-118.32,34.11,42.0,2462.0,543.0,857.0,482.0,4.0833,<1H OCEAN
6084,-117.89,34.09,36.0,1811.0,320.0,1005.0,332.0,5.5629,<1H OCEAN
...,...,...,...,...,...,...,...,...,...
6460,-118.05,34.10,36.0,1606.0,318.0,889.0,294.0,4.7931,INLAND
18375,-121.85,37.22,21.0,6203.0,798.0,2494.0,800.0,7.7201,<1H OCEAN
11212,-117.91,33.82,29.0,1444.0,326.0,1038.0,271.0,2.3843,<1H OCEAN
20291,-119.19,34.17,35.0,4276.0,767.0,3295.0,708.0,4.2583,NEAR OCEAN
6340,-117.90,33.98,20.0,9893.0,2283.0,7228.0,2159.0,3.2530,<1H OCEAN

In [67]:
num_features = X_train.select_dtypes('float').columns
cat_features = X_train.select_dtypes('object').columns

In [68]:
num_features

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype='object')

In [69]:
cat_features

Index(['ocean_proximity'], dtype='object')

In [61]:
from sklearn.compose import ColumnTransformer

In [73]:
final_pipeline = ColumnTransformer([
    ('num_pipeline', num_pipeline, num_features),
    ('cat_pipeline', cat_pipeline, cat_features)
])
final_pipeline

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('impute',
                                                  SimpleImputer(strategy='median')),
                                                 ('scale', StandardScaler())]),
                                 Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype='object')),
                                ('cat_pipeline',
                                 Pipeline(steps=[('impute',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OrdinalEncoder())]),
                                 Index(['ocean_proximity'], dtype='object'))])

In [74]:
final_pipeline.fit(X_train)
X_train_tr = final_pipeline.transform(X_train)
X_test_tr = final_pipeline.transform(X_test)

In [75]:
X_train_tr

array([[ 0.66136173, -0.69064867, -1.71479173, ...,  0.38008101,
        -1.12465992,  0.        ],
       [-1.25933122,  0.97054898, -0.28418936, ...,  0.55678574,
        -0.19477467,  3.        ],
       [ 0.96147001, -0.92462017, -1.95322546, ...,  2.47943863,
         0.81764165,  0.        ],
       ...,
       [-0.98923378,  0.63830945, -0.12523354, ..., -0.26871543,
        -0.31712105,  1.        ],
       [ 0.65135812, -0.72808411,  0.90797928, ..., -0.65904826,
        -0.8448453 ,  0.        ],
       [ 0.77640324, -0.85910815,  0.11320019, ..., -0.2739902 ,
         0.83029817,  0.        ]])

In [76]:
X_test_tr

array([[-1.4493998 ,  0.94715183, -0.99949055, ...,  2.83548546,
         0.49933011,  4.        ],
       [-1.27433664,  0.84420437,  0.51058973, ...,  0.14271646,
         1.81951086,  3.        ],
       [-1.3443619 ,  1.00330499,  1.8617142 , ..., -0.142121  ,
        -0.31337683,  3.        ],
       ...,
       [ 0.82642128, -0.84506986,  0.03372228, ..., -0.60102581,
        -0.77966421,  0.        ],
       [ 0.1861903 , -0.68128981,  0.51058973, ...,  0.55151097,
         0.20859924,  4.        ],
       [ 0.83142309, -0.77019898, -0.68157891, ...,  4.37835506,
        -0.32155084,  0.        ]])

In [78]:
final_pipeline.named_transformers_

{'num_pipeline': Pipeline(steps=[('impute', SimpleImputer(strategy='median')),
                 ('scale', StandardScaler())]),
 'cat_pipeline': Pipeline(steps=[('impute', SimpleImputer(strategy='most_frequent')),
                 ('encoder', OrdinalEncoder())])}

In [79]:
final_pipeline.named_transformers_.num_pipeline

Pipeline(steps=[('impute', SimpleImputer(strategy='median')),
                ('scale', StandardScaler())])

In [82]:
num_cols = final_pipeline.named_transformers_.num_pipeline.get_feature_names_out()
num_cols

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [83]:
cat_cols = final_pipeline.named_transformers_.cat_pipeline.get_feature_names_out()
cat_cols

array(['ocean_proximity'], dtype=object)

In [85]:
cols = np.append(num_cols, cat_cols)
cols

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity'], dtype=object)

In [86]:
pd.DataFrame(X_train_tr, columns=cols)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,0.661362,-0.690649,-1.714792,-0.262430,0.321892,0.412041,0.380081,-1.124660,0.0
1,-1.259331,0.970549,-0.284189,0.354582,0.533365,0.194575,0.556786,-0.194775,3.0
2,0.961470,-0.924620,-1.953225,1.939735,2.345307,1.612946,2.479439,0.817642,0.0
3,0.341246,-0.662572,-0.204711,-0.480389,-0.817180,-0.677931,-0.790917,1.435649,0.0
4,0.686371,-0.732764,0.669546,-0.422789,-0.192372,0.552909,-0.155308,-0.817528,0.0
...,...,...,...,...,...,...,...,...,...
16507,-1.564441,1.316827,0.192678,-0.379934,-0.531210,-0.645355,-0.577289,-0.002343,0.0
16508,0.506306,-0.653213,-0.284189,0.818608,1.158173,2.777754,1.348001,-0.522104,0.0
16509,-0.989234,0.638309,-0.125234,-0.125112,-0.209194,0.315193,-0.268715,-0.317121,1.0
16510,0.651358,-0.728084,0.907979,-0.899717,-0.632141,-0.377704,-0.659048,-0.844845,0.0
16511,0.776403,-0.859108,0.113200,-0.079492,-0.319737,-0.129423,-0.273990,0.830298,0.0

In [87]:
pd.DataFrame(X_test_tr, columns=cols)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-1.449400,0.947152,-0.999491,2.784843,2.636082,3.262870,2.835485,0.499330,4.0
1,-1.274337,0.844204,0.510590,0.586364,0.069566,0.121499,0.142716,1.819511,3.0
2,-1.344362,1.003305,1.861714,-0.219576,-0.187566,-0.485997,-0.142121,-0.313377,3.0
3,0.621347,-0.709366,1.066935,-0.078571,0.016698,-0.499204,-0.044538,0.116312,0.0
4,0.836425,-0.718725,0.590068,-0.378552,-0.519195,-0.368900,-0.440145,0.896587,0.0
...,...,...,...,...,...,...,...,...,...
4123,0.756396,-0.714046,0.590068,-0.473016,-0.524001,-0.471030,-0.540366,0.490629,1.0
4124,-1.144290,0.745936,-0.602101,1.645284,0.629490,0.942059,0.794150,2.034197,0.0
4125,0.826421,-0.845070,0.033722,-0.547666,-0.504776,-0.339846,-0.601026,-0.779664,0.0
4126,0.186190,-0.681290,0.510590,0.757321,0.554993,1.647283,0.551511,0.208599,4.0
4127,0.831423,-0.770199,-0.681579,3.345637,4.198101,5.110011,4.378355,-0.321551,0.0

In [94]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor


house = pd.read_csv('housing.csv')

X = house.drop('median_house_value', axis=1)
y = house.median_house_value


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=121)


num_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy='median')),
    ('scale', StandardScaler())
])

cat_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder())
])


final_pipeline = ColumnTransformer([
    ('num_pipeline', num_pipeline, num_features),
    ('cat_pipeline', cat_pipeline, cat_features)
])


final_pipeline.fit(X_train)
X_train_tr = final_pipeline.transform(X_train)
X_test_tr = final_pipeline.transform(X_test)


models = [
    ('linear', LinearRegression()),
    ('SGD', SGDRegressor()),
    ('forest', RandomForestRegressor()),
    ('SVM', SVR()),
    ('KNN', KNeighborsRegressor())
]

In [99]:
def model_report(models, X_train, X_test, y_train, y_test):
    for name, model in models:
        print(f'Model_name: {name}')
        model.fit(X_train, y_train)
        y_train_hat = model.predict(X_train)
        y_test_hat = model.predict(X_test)
        
        print(f"Training Accuracy: {r2_score(y_train, y_train_hat)}")
        print(f"Training error: {mean_squared_error(y_train, y_train_hat)}")
        print()
        print(f"Testing Accuracy: {r2_score(y_test, y_test_hat)}")
        print(f"Testing error: {mean_squared_error(y_test, y_test_hat)}")
        print()

In [98]:
model_report(models, X_train_tr, X_test_tr, y_train, y_test)

Model_name: linear
Training Accuracy: 0.6302837145718101
Training error: 4926615676.883583

Testing Accuracy: 0.6565099331108482
Testing error: 4559838180.699618

Model_name: SGD
Training Accuracy: 0.6299502851700369
Training error: 4931058755.489132

Testing Accuracy: 0.6563642608843558
Testing error: 4561771982.70514

Model_name: forest
Training Accuracy: 0.9744010800542258
Training error: 341115729.2410772

Testing Accuracy: 0.8233220409049945
Testing error: 2345403786.682062

Model_name: SVM
Training Accuracy: -0.05032844554893323
Training error: 13996041801.959507

Testing Accuracy: -0.05494720894770455
Testing error: 14004447364.513191

Model_name: KNN
Training Accuracy: 0.8142583428559944
Training error: 2475081017.5326424

Testing Accuracy: 0.7291625186187569
Testing error: 3595373512.6939054

In [2]:
%%writefile model_evaluation.py

from sklearn.metrics import r2_score, mean_squared_error

def model_report(models, X_train, X_test, y_train, y_test):
    for name, model in models:
        print(f'Model_name: {name}')
        model.fit(X_train, y_train)
        y_train_hat = model.predict(X_train)
        y_test_hat = model.predict(X_test)
        
        print(f"Training Accuracy: {r2_score(y_train, y_train_hat)}")
        print(f"Training error: {mean_squared_error(y_train, y_train_hat)}")
        print()
        print(f"Testing Accuracy: {r2_score(y_test, y_test_hat)}")
        print(f"Testing error: {mean_squared_error(y_test, y_test_hat)}")
        print()

Overwriting model_evaluation.py