In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
house = pd.read_csv('housing.csv')
house

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [3]:
house.dropna(inplace=True)

In [4]:
house

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [5]:
house.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [6]:
X = house.drop(['median_house_value', 'ocean_proximity'], axis=1)
y = house.median_house_value

In [7]:
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462
...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886

In [8]:
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20433, dtype: float64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=121)

In [11]:
X_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
6644,-118.15,34.16,20.0,2410.0,632.0,2135.0,578.0,1.6887
11521,-118.06,33.73,16.0,4392.0,602.0,1490.0,578.0,10.5424
8026,-118.11,33.83,36.0,1784.0,303.0,964.0,299.0,4.2703
7575,-118.21,33.88,38.0,929.0,166.0,686.0,183.0,3.4485
20557,-121.78,38.68,43.0,3766.0,847.0,1855.0,817.0,2.3468
...,...,...,...,...,...,...,...,...
19385,-120.85,37.77,20.0,651.0,157.0,421.0,151.0,2.0833
3613,-118.41,34.23,35.0,1026.0,195.0,753.0,185.0,4.5909
18675,-121.88,36.96,18.0,6355.0,1100.0,2304.0,972.0,6.0281
4610,-118.29,34.07,19.0,3013.0,1118.0,2465.0,1008.0,2.5386
11702,-117.97,33.89,15.0,3801.0,542.0,1992.0,526.0,9.0683

In [12]:
y_train

6644     148600.0
11521    500001.0
8026     220900.0
7575     119400.0
20557    119400.0
           ...
19385     77300.0
3613     179200.0
18675    321100.0
4610     290600.0
11702    367400.0
Name: median_house_value, Length: 16346, dtype: float64

In [13]:
X_test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
14821,-117.11,32.67,52.0,204.0,74.0,248.0,57.0,1.7961
14126,-117.08,32.75,15.0,1821.0,516.0,1385.0,439.0,2.5101
1842,-122.29,37.91,40.0,2085.0,329.0,796.0,339.0,5.5357
19125,-122.64,38.25,31.0,2554.0,515.0,1507.0,533.0,3.8000
5318,-118.42,34.06,44.0,533.0,90.0,291.0,97.0,10.8045
...,...,...,...,...,...,...,...,...
17714,-121.79,37.34,20.0,2018.0,328.0,1196.0,323.0,4.9318
20511,-121.54,38.59,40.0,2120.0,504.0,1304.0,464.0,2.0368
9905,-122.27,38.31,44.0,3030.0,589.0,1373.0,582.0,2.9054
7518,-118.25,33.91,35.0,1479.0,272.0,963.0,292.0,3.4917
12603,-121.47,38.53,43.0,3215.0,725.0,2400.0,625.0,1.4625

In [14]:
y_test

14821     47500.0
14126     95300.0
1842     273700.0
19125    162600.0
5318     500001.0
           ...
17714    262400.0
20511     67800.0
9905     155200.0
7518     109500.0
12603     54400.0
Name: median_house_value, Length: 4087, dtype: float64

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
model = LinearRegression()

In [18]:
model

LinearRegression()

In [19]:
model.fit(X_train, y_train)

LinearRegression()

In [20]:
model.coef_

array([-4.21537287e+04, -4.21442932e+04,  1.14386878e+03, -7.94890099e+00,
        1.09729463e+02, -4.33303591e+01,  6.24483231e+01,  4.02221203e+04])

In [22]:
model.intercept_

-3527796.3981583053

In [23]:
y_train_hat = model.predict(X_train)
y_train_hat

array([ 97595.04606439, 472363.84386504, 234147.62692178, ...,
       346353.34747504, 201419.55796053, 374506.50468202])

In [24]:
y_train

6644     148600.0
11521    500001.0
8026     220900.0
7575     119400.0
20557    119400.0
           ...
19385     77300.0
3613     179200.0
18675    321100.0
4610     290600.0
11702    367400.0
Name: median_house_value, Length: 16346, dtype: float64

In [25]:
y_test_hat = model.predict(X_test)
y_test_hat

array([163008.8681825 , 155003.85280804, 304111.8230011 , ...,
       196381.53756814, 202845.78738096,  65844.10335635])

In [26]:
y_test

14821     47500.0
14126     95300.0
1842     273700.0
19125    162600.0
5318     500001.0
           ...
17714    262400.0
20511     67800.0
9905     155200.0
7518     109500.0
12603     54400.0
Name: median_house_value, Length: 4087, dtype: float64

In [27]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [28]:
y_train

6644     148600.0
11521    500001.0
8026     220900.0
7575     119400.0
20557    119400.0
           ...
19385     77300.0
3613     179200.0
18675    321100.0
4610     290600.0
11702    367400.0
Name: median_house_value, Length: 16346, dtype: float64

In [29]:
y_train_hat

array([ 97595.04606439, 472363.84386504, 234147.62692178, ...,
       346353.34747504, 201419.55796053, 374506.50468202])

In [32]:
print(f"Training Accuracy: {r2_score(y_train, y_train_hat)}")
print(f"Training Error: {mean_squared_error(y_train, y_train_hat)}")

Training Accuracy: 0.6355837452268782
Training Error: 4863151899.7727995

In [28]:
r2_score(y_train, y_train_hat)

0.6355837452268782

In [33]:
y_test

14821     47500.0
14126     95300.0
1842     273700.0
19125    162600.0
5318     500001.0
           ...
17714    262400.0
20511     67800.0
9905     155200.0
7518     109500.0
12603     54400.0
Name: median_house_value, Length: 4087, dtype: float64

In [34]:
y_test_hat

array([163008.8681825 , 155003.85280804, 304111.8230011 , ...,
       196381.53756814, 202845.78738096,  65844.10335635])

In [35]:
print(f"Testing Accuracy: {r2_score(y_test, y_test_hat)}")
print(f"Testing Error: {mean_squared_error(y_test, y_test_hat)}")

Testing Accuracy: 0.6401738148880879
Testing Error: 4765234910.146864